import "./globals.css";
import Topo from "@/componentes/Topo";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Topo>
            <Link href="#">Home</Link>
            <Link href="#">About</Link>
            <Link href="#">Elements</Link>
            <Link href="#">Gallery</Link>
        </Topo>
        {children}
      </body>
    </html>
  );
}